//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIArtist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public System.Guid ArtisteId { get; set; }
        public string ArtisteName { get; set; }
        public string? Country { get; set; }
        public string? Aliases { get; set; }
    }
}
